import { Equipment, StockMovement, Request } from '../types';

export const mockEquipment: Equipment[] = [
  {
    id: '1',
    name: 'Luvas de Látex',
    code: 'LAT001',
    category: 'general',
    quantity: 150,
    unit: 'caixas',
    supplier: 'MedSupply',
    batch: 'LT240315',
    entryDate: '2024-03-15',
    expirationDate: '2025-03-15',
    location: 'Prateleira A1',
    minStock: 20,
    status: 'active',
    unitPrice: 45.00,
    totalValue: 6750.00,
    invoiceNumber: 'NF-2024-001',
    isWithholding: false,
    supplierId: 'sup-1',
    supplierName: 'MedSupply Ltda',
  },
  {
    id: '2',
    name: 'Reagente pH Buffer',
    code: 'RBF002',
    category: 'technical',
    quantity: 5,
    unit: 'litros',
    supplier: 'ChemLab',
    batch: 'PH240220',
    entryDate: '2024-02-20',
    expirationDate: '2024-12-20',
    location: 'Geladeira B2',
    minStock: 10,
    status: 'low-stock',
    unitPrice: 120.00,
    totalValue: 600.00,
    invoiceNumber: 'NF-2024-002',
    isWithholding: true,
    supplierId: 'sup-2',
    supplierName: 'ChemLab Indústria',
  },
  {
    id: '3',
    name: 'Papel de Filtro',
    code: 'PAP003',
    category: 'general',
    quantity: 80,
    unit: 'pacotes',
    supplier: 'LabSupply',
    batch: 'PF240410',
    entryDate: '2024-04-10',
    expirationDate: '2026-04-10',
    location: 'Armário C3',
    minStock: 15,
    status: 'active',
    unitPrice: 25.00,
    totalValue: 2000.00,
    invoiceNumber: 'NF-2024-003',
    isWithholding: false,
    supplierId: 'sup-3',
    supplierName: 'LabSupply Comércio',
  },
  {
    id: '4',
    name: 'Solução Salina',
    code: 'SOL004',
    category: 'technical',
    quantity: 3,
    unit: 'frascos',
    supplier: 'BioTech',
    batch: 'SS241101',
    entryDate: '2024-11-01',
    expirationDate: '2024-12-30',
    location: 'Prateleira D1',
    minStock: 8,
    status: 'expired',
    unitPrice: 85.00,
    totalValue: 255.00,
    invoiceNumber: 'NF-2024-004',
    isWithholding: false,
    supplierId: 'sup-4',
    supplierName: 'BioTech SA',
  }
];

export const mockMovements: StockMovement[] = [
  {
    id: '1',
    equipmentId: '1',
    equipmentName: 'Luvas de Látex',
    type: 'out',
    reason: 'internal-consumption',
    quantity: 5,
    date: '2024-12-20',
    authorizedBy: 'Dr. Silva',
    notes: 'Uso rotina laboratório',
    unitPrice: 45.00,
    totalValue: 225.00,
  },
  {
    id: '2',
    equipmentId: '2',
    equipmentName: 'Reagente pH Buffer',
    type: 'out',
    reason: 'sale',
    quantity: 2,
    date: '2024-12-19',
    requestId: 'REQ001',
    authorizedBy: 'Dr. Santos',
    notes: 'Venda cliente externo',
    unitPrice: 120.00,
    totalValue: 240.00,
  }
];

export const mockRequests: Request[] = [
  {
    id: 'REQ001',
    type: 'SC',
    items: [
      {
        id: 'item-1',
        equipmentId: '2',
        equipmentName: 'Reagente pH Buffer',
        quantity: 2,
        category: 'technical',
      }
    ],
    reason: 'Venda para cliente externo',
    requestedBy: 'João Silva',
    requestDate: '2024-12-18',
    status: 'completed',
    priority: 'standard',
    approvedBy: 'Dr. Santos',
    approvalDate: '2024-12-19',
  },
  {
    id: 'REQ002',
    type: 'SC',
    items: [
      {
        id: 'item-2',
        equipmentId: '3',
        equipmentName: 'Papel de Filtro',
        quantity: 10,
        category: 'general',
      }
    ],
    reason: 'Transferência para filial',
    requestedBy: 'Maria Costa',
    requestDate: '2024-12-20',
    status: 'pending',
    priority: 'standard',
  }
];
